-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public._backup_dispatch_entry_time_fix (
  id uuid,
  original_entry_time timestamp with time zone,
  created_at timestamp with time zone
);
CREATE TABLE public._tmp_sheet_dates (
  firebase_id text NOT NULL,
  sheet_issue text,
  sheet_expiry text,
  CONSTRAINT _tmp_sheet_dates_pkey PRIMARY KEY (firebase_id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action character varying NOT NULL,
  user_id uuid,
  old_values jsonb,
  new_values jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bieu_do_chay_buyt (
  id character varying NOT NULL,
  tuyen_buyt_id character varying NOT NULL,
  don_vi_khai_thac text,
  qd_khai_thac text,
  ngay_ap_dung date,
  related_giochay_buyts text,
  related_giochay_buyt_ids ARRAY,
  user_nhap text,
  thoi_gian_nhap text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bieu_do_chay_buyt_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bieu_do_chay_xe_chi_tiet (
  id character varying NOT NULL,
  ref_thongbao_khaithac character varying NOT NULL,
  chieu text,
  gio_xuat_ben time without time zone NOT NULL,
  ngay_hoat_dong text,
  loai_ngay text,
  trang_thai_chuyen text,
  so_chuyen_thang integer,
  ghi_chu text,
  so_thong_bao text,
  ngay_hoat_dong_goc text,
  ngay_bi_ngung text,
  trang_thai_tong_hop text,
  lan_dieu_chinh_cuoi text,
  ref_van_ban_dieu_chinh_cuoi text,
  lich_chieu text,
  ten_tuyen_hien_thi text,
  so_chuyen_khai_thac text,
  vc_phieu_giam_tan_suat_moi_nhat text,
  vc_ngay_hoat_dong_moi text,
  vc_van_ban_dieu_chinh_moi_nhat text,
  bieu_do_hien_thi text,
  vc_vb_cham_dut_moi_nhat text,
  related_phieu_giam_tan_suat_bieu_dos text,
  related_ls_giam_tan_suat_bieu_dos text,
  user_nhap text,
  thoi_gian_nhap text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bieu_do_chay_xe_chi_tiet_pkey PRIMARY KEY (id)
);
CREATE TABLE public.danh_muc_tuyen_bus (
  id_tuyen character varying NOT NULL,
  noi_di character varying,
  noi_den character varying,
  diem_dau character varying,
  diem_cuoi character varying,
  cu_ly numeric,
  hanh_trinh text,
  so_hieu_tuyen character varying,
  tro_gia character varying,
  qd_cong_bo_danh_muc character varying,
  link_qd_danh_muc text,
  so_chuyen_theo_qh integer,
  so_chuyen_da_kt integer,
  ghi_chu text,
  trang_thai character varying,
  CONSTRAINT danh_muc_tuyen_bus_pkey PRIMARY KEY (id_tuyen)
);
CREATE TABLE public.danhmuc_tuyen_buyt (
  id character varying NOT NULL,
  so_hieu_tuyen text,
  noi_di text,
  noi_den text,
  diem_dau text,
  diem_cuoi text,
  cu_ly numeric,
  hanh_trinh text,
  tro_gia text,
  qd_cong_bo_danh_muc text,
  link_qd_danh_muc text,
  so_chuyen_theo_qh integer,
  so_chuyen_da_kt integer,
  ghi_chu text,
  trang_thai text,
  so_chuyen_chua_khai_thac integer,
  ten_hien_thi_tuyen text,
  related_bieudo_buyt_ids text,
  related_phuhieuxe_ids text,
  user_nhap text,
  thoi_gian_nhap text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT danhmuc_tuyen_buyt_pkey PRIMARY KEY (id)
);
CREATE TABLE public.danhmuc_tuyen_codinh (
  id character varying NOT NULL,
  ma_so_tuyen text NOT NULL UNIQUE,
  ten_tuyen text,
  tinh_di text,
  tinh_den text,
  ben_di text,
  ben_di_ref text,
  ben_den text,
  ben_den_ref text,
  hanh_trinh text,
  cu_ly_tuyen_km numeric,
  tong_chuyen_thang integer,
  chuyen_da_khai_thac integer,
  luu_luong_con_lai integer,
  gian_cach_toi_thieu_phut integer,
  phan_loai_tuyen text,
  tinh_trang_khai_thac text,
  so_quyet_dinh text,
  ngay_ban_hanh date,
  don_vi_ban_hanh text,
  file_van_ban text,
  thong_tin_tuyen_goc text,
  ma_so_tuyen_fix text,
  ma_so_tuyen_cu text,
  tinh_di_cu text,
  tinh_den_cu text,
  kieulich text,
  ghi_chu_mo_rong text,
  id_bao_cao_cuc_hieu_luc text,
  ngay_ap_dung_hien_tai text,
  vb_cong_bo text,
  file_vbcb text,
  so_ph_con_hieu_luc text,
  dang_khai_thac text,
  co_don_vi_trong_tinh_khai_thac text,
  co_don_vi_ngoai_tinh_khai_thac text,
  nhom_khai_thac text,
  tinh_di_o text,
  tinh_di_n text,
  tinh_den_f_o text,
  tinh_den_n text,
  ben_di_o text,
  ben_di_n text,
  ben_den_o text,
  ben_den_n text,
  ma_o text,
  related_phuhieuxes text,
  related_thongbao_khaithacs text,
  related_ls_vanban_tuyen_codinhs text,
  dots_da_chot text,
  dot_dang_mo text,
  id_bao_cao_cuc_moi_nhat text,
  user_nhap text,
  thoi_gian_nhap text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT danhmuc_tuyen_codinh_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dependents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  hotennpt character varying NOT NULL,
  ngaysinhnpt date NOT NULL,
  socccdnpt character varying,
  mstnpt character varying,
  quanhe character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dependents_pkey PRIMARY KEY (id),
  CONSTRAINT dependents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.nhan_su(id)
);
CREATE TABLE public.dispatch_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  vehicle_id uuid,
  driver_id uuid,
  route_id uuid,
  operator_id uuid,
  user_id uuid,
  shift_id uuid,
  status character varying NOT NULL DEFAULT 'entered'::character varying,
  entry_time timestamp with time zone,
  exit_time timestamp with time zone,
  departure_time timestamp with time zone,
  passenger_drop_time timestamp with time zone,
  permit_issued_time timestamp with time zone,
  payment_time timestamp with time zone,
  passengers integer DEFAULT 0,
  passenger_manifest jsonb,
  fare numeric,
  total_amount numeric,
  service_charges jsonb,
  permit_number character varying,
  departure_order_number character varying,
  notes text,
  rejection_reason text,
  vehicle_plate_number character varying,
  vehicle_seat_count integer,
  driver_name character varying,
  driver_phone character varying,
  operator_name character varying,
  operator_code character varying,
  route_code character varying,
  route_name character varying,
  departure_station character varying,
  arrival_station character varying,
  created_by_name character varying,
  is_active boolean NOT NULL DEFAULT true,
  is_deleted boolean DEFAULT false,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  permit_status character varying,
  entry_by_name character varying,
  entry_shift_id uuid,
  entry_image_url text,
  passenger_drop_by uuid,
  passenger_drop_by_name character varying,
  boarding_permit_by uuid,
  boarding_permit_by_name character varying,
  permit_shift_id uuid,
  planned_departure_time timestamp with time zone,
  transport_order_code character varying,
  seat_count integer,
  payment_method character varying,
  invoice_number character varying,
  payment_by uuid,
  payment_by_name character varying,
  payment_shift_id uuid,
  passengers_departing integer,
  departure_order_by uuid,
  departure_order_by_name character varying,
  departure_order_shift_id uuid,
  exit_by_name character varying,
  exit_shift_id uuid,
  vehicle_operator_name character varying,
  vehicle_operator_code character varying,
  route_destination_id uuid,
  route_destination_name character varying,
  route_destination_code character varying,
  schedule_id uuid,
  entry_by uuid,
  passengers_arrived integer,
  boarding_permit_time timestamp with time zone,
  payment_amount numeric,
  departure_order_time timestamp with time zone,
  exit_by uuid,
  vehicle_operator_id uuid,
  route_type character varying,
  driver_full_name character varying,
  CONSTRAINT dispatch_records_pkey PRIMARY KEY (id),
  CONSTRAINT dispatch_records_vehicle_id_vehicles_id_fk FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT dispatch_records_driver_id_drivers_id_fk FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT dispatch_records_route_id_routes_id_fk FOREIGN KEY (route_id) REFERENCES public.routes(id),
  CONSTRAINT dispatch_records_operator_id_operators_id_fk FOREIGN KEY (operator_id) REFERENCES public.operators(id),
  CONSTRAINT dispatch_records_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT dispatch_records_shift_id_shifts_id_fk FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT dispatch_records_entry_shift_id_fkey FOREIGN KEY (entry_shift_id) REFERENCES public.shifts(id),
  CONSTRAINT dispatch_records_passenger_drop_by_fkey FOREIGN KEY (passenger_drop_by) REFERENCES public.users(id),
  CONSTRAINT dispatch_records_boarding_permit_by_fkey FOREIGN KEY (boarding_permit_by) REFERENCES public.users(id),
  CONSTRAINT dispatch_records_permit_shift_id_fkey FOREIGN KEY (permit_shift_id) REFERENCES public.shifts(id),
  CONSTRAINT dispatch_records_payment_by_fkey FOREIGN KEY (payment_by) REFERENCES public.users(id),
  CONSTRAINT dispatch_records_payment_shift_id_fkey FOREIGN KEY (payment_shift_id) REFERENCES public.shifts(id),
  CONSTRAINT dispatch_records_departure_order_by_fkey FOREIGN KEY (departure_order_by) REFERENCES public.users(id),
  CONSTRAINT dispatch_records_departure_order_shift_id_fkey FOREIGN KEY (departure_order_shift_id) REFERENCES public.shifts(id),
  CONSTRAINT dispatch_records_exit_shift_id_fkey FOREIGN KEY (exit_shift_id) REFERENCES public.shifts(id),
  CONSTRAINT dispatch_records_entry_by_fkey FOREIGN KEY (entry_by) REFERENCES public.users(id),
  CONSTRAINT dispatch_records_exit_by_fkey FOREIGN KEY (exit_by) REFERENCES public.users(id)
);
CREATE TABLE public.driver_operators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  operator_id uuid NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_operators_pkey PRIMARY KEY (id),
  CONSTRAINT driver_operators_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT driver_operators_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.operators(id)
);
CREATE TABLE public.drivers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  full_name character varying NOT NULL,
  phone character varying,
  id_number character varying,
  operator_id uuid,
  license_number character varying,
  license_class character varying,
  license_expiry_date date,
  date_of_birth date,
  address character varying,
  is_active boolean NOT NULL DEFAULT true,
  operator_name character varying,
  operator_code character varying,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  province character varying,
  district character varying,
  image_url text,
  CONSTRAINT drivers_pkey PRIMARY KEY (id),
  CONSTRAINT drivers_operator_id_operators_id_fk FOREIGN KEY (operator_id) REFERENCES public.operators(id)
);
CREATE TABLE public.gio_chay_buyt (
  id character varying NOT NULL,
  bieu_do_id character varying NOT NULL,
  chieu text,
  gio_xuat_ben time without time zone NOT NULL,
  ghi_chu text,
  user_nhap text,
  thoi_gian_nhap text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gio_chay_buyt_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hop_dong (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  customer_name character varying,
  project_name character varying,
  so_hop_dong character varying,
  ten_goi_thau text,
  ngay_ky_hd date,
  file_status text,
  progress integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gia_tri_hd numeric DEFAULT 0,
  gia_tri_qt numeric DEFAULT 0,
  da_thu numeric DEFAULT 0,
  con_phai_thu numeric DEFAULT 0,
  loai_dich_vu text,
  ngay_update date,
  phan_tram_task_hoan_thanh integer DEFAULT 0,
  CONSTRAINT hop_dong_pkey PRIMARY KEY (id),
  CONSTRAINT fk_hop_dong_khach_hang FOREIGN KEY (customer_id) REFERENCES public.khach_hang(id)
);
CREATE TABLE public.id_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying NOT NULL,
  postgres_id uuid NOT NULL,
  entity_type character varying NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT id_mappings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  dispatch_record_id uuid,
  operator_id uuid,
  invoice_number character varying UNIQUE,
  invoice_date timestamp with time zone,
  subtotal numeric,
  tax numeric,
  total_amount numeric,
  payment_status character varying DEFAULT 'pending'::character varying,
  payment_method character varying,
  paid_at timestamp with time zone,
  notes text,
  status character varying DEFAULT 'draft'::character varying,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_dispatch_record_id_dispatch_records_id_fk FOREIGN KEY (dispatch_record_id) REFERENCES public.dispatch_records(id),
  CONSTRAINT invoices_operator_id_operators_id_fk FOREIGN KEY (operator_id) REFERENCES public.operators(id)
);
CREATE TABLE public.khach_hang (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ten_don_vi character varying NOT NULL,
  loai_hinh character varying,
  mst character varying,
  dia_chi text,
  nguoi_dai_dien character varying,
  chuc_vu_dai_dien character varying,
  nguoi_lien_he character varying,
  chuc_vu_lien_he character varying,
  sdt_lien_he character varying,
  tong_hop_dong numeric DEFAULT 0,
  gia_tri_quyet_toan numeric DEFAULT 0,
  da_thu numeric DEFAULT 0,
  con_phai_thu numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT khach_hang_pkey PRIMARY KEY (id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  code character varying NOT NULL UNIQUE,
  station_type character varying,
  phone character varying,
  email character varying,
  address text,
  latitude numeric,
  longitude numeric,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  ma_ben text,
  CONSTRAINT locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nhan_su (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying UNIQUE,
  full_name character varying,
  name character varying,
  hoten character varying,
  department character varying,
  phongban character varying,
  position character varying,
  chucvu character varying,
  email character varying,
  phone character varying,
  sdtnhanvien character varying,
  status character varying DEFAULT 'active'::character varying,
  joindate date,
  ngayvaolam date,
  ngaysinh date,
  diachi text,
  socccd character varying,
  ngaycapcccd date,
  mstcanhan character varying,
  masobhxh character varying,
  bangdhchuyennganh character varying,
  namtotnghiep integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nhan_su_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nhan_su_chi_tiet (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_nhan_su uuid NOT NULL,
  ten_file_luu character varying,
  file_url text,
  anh_url text,
  anh2_url text,
  ghi_chu text,
  cchn character varying,
  hang_cchn character varying,
  ngay_het_han_cc date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nhan_su_chi_tiet_pkey PRIMARY KEY (id),
  CONSTRAINT nhan_su_chi_tiet_id_nhan_su_fkey FOREIGN KEY (id_nhan_su) REFERENCES public.nhan_su(id)
);
CREATE TABLE public.operation_notices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_code character varying NOT NULL,
  operator_ref character varying,
  notice_number character varying NOT NULL,
  issue_date character varying,
  effective_date character varying,
  file_path text,
  file_url text,
  issuing_authority character varying,
  status character varying DEFAULT 'Con hieu luc'::character varying,
  notice_type character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT operation_notices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.operators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  short_name character varying,
  address text,
  phone character varying,
  email character varying,
  tax_code character varying,
  representative character varying,
  business_license character varying,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb,
  synced_at timestamp with time zone,
  source character varying DEFAULT 'manual'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  representative_position character varying,
  province character varying,
  district character varying,
  is_ticket_delegated boolean DEFAULT false,
  CONSTRAINT operators_pkey PRIMARY KEY (id)
);
CREATE TABLE public.routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  route_code character varying NOT NULL UNIQUE,
  route_code_old character varying,
  departure_province character varying,
  departure_station character varying,
  departure_station_ref character varying,
  arrival_province character varying,
  arrival_station character varying,
  arrival_station_ref character varying,
  distance_km integer,
  itinerary text,
  route_type character varying,
  total_trips_per_month integer,
  trips_operated integer,
  remaining_capacity integer,
  min_interval_minutes integer,
  decision_number character varying,
  decision_date character varying,
  issuing_authority character varying,
  operation_status character varying,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb,
  synced_at timestamp with time zone,
  source character varying DEFAULT 'manual'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT routes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  schedule_code character varying NOT NULL UNIQUE,
  route_id uuid NOT NULL,
  operator_id uuid NOT NULL,
  departure_time time without time zone NOT NULL,
  frequency_type character varying NOT NULL CHECK (frequency_type::text = ANY (ARRAY['daily'::character varying::text, 'weekly'::character varying::text, 'specific_days'::character varying::text])),
  days_of_week jsonb,
  effective_from character varying NOT NULL,
  effective_to character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  firebase_id character varying UNIQUE,
  direction character varying,
  days_of_month jsonb,
  calendar_type character varying,
  notification_number character varying,
  trip_status character varying,
  source character varying DEFAULT 'manual'::character varying,
  synced_at timestamp with time zone,
  metadata jsonb,
  CONSTRAINT schedules_pkey PRIMARY KEY (id),
  CONSTRAINT schedules_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id),
  CONSTRAINT schedules_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.operators(id)
);
CREATE TABLE public.service_charges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispatch_record_id uuid NOT NULL,
  service_id uuid NOT NULL,
  quantity numeric NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_amount numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_charges_pkey PRIMARY KEY (id),
  CONSTRAINT service_charges_dispatch_record_id_fkey FOREIGN KEY (dispatch_record_id) REFERENCES public.dispatch_records(id),
  CONSTRAINT service_charges_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.service_formula_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_id uuid NOT NULL,
  formula_id uuid NOT NULL,
  usage_type character varying NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_formula_usage_pkey PRIMARY KEY (id),
  CONSTRAINT service_formula_usage_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT service_formula_usage_formula_id_fkey FOREIGN KEY (formula_id) REFERENCES public.service_formulas(id)
);
CREATE TABLE public.service_formulas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description character varying,
  formula_type character varying NOT NULL,
  formula_expression character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_formulas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  unit character varying NOT NULL,
  tax_percentage numeric NOT NULL DEFAULT 0,
  material_type character varying NOT NULL,
  use_quantity_formula boolean NOT NULL DEFAULT false,
  use_price_formula boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  is_default boolean NOT NULL DEFAULT false,
  auto_calculate_quantity boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  description character varying,
  base_price numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.setting (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying UNIQUE,
  theme character varying DEFAULT 'light'::character varying,
  color character varying DEFAULT 'blue'::character varying,
  font_family character varying DEFAULT 'Inter'::character varying,
  font_size character varying DEFAULT 'Trung bình'::character varying,
  language character varying DEFAULT 'vi'::character varying,
  logo_url text,
  timezone character varying DEFAULT '(GMT+07:00) Hà Nội, TP HCM, Bangkok'::character varying,
  email_notifications boolean DEFAULT false,
  push_notifications boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT setting_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  name character varying NOT NULL,
  code character varying UNIQUE,
  start_time time without time zone,
  end_time time without time zone,
  description character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shifts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.task (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hop_dong_id uuid NOT NULL,
  ten_task character varying NOT NULL,
  mo_ta text,
  trang_thai character varying DEFAULT 'Chưa bắt đầu'::character varying,
  uu_tien character varying DEFAULT 'Trung bình'::character varying,
  ngay_bat_dau date,
  ngay_ket_thuc date,
  ngay_hoan_thanh date,
  nguoi_phu_trach character varying,
  tien_do integer DEFAULT 0,
  ghi_chu text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT task_pkey PRIMARY KEY (id),
  CONSTRAINT fk_task_hop_dong FOREIGN KEY (hop_dong_id) REFERENCES public.hop_dong(id)
);
CREATE TABLE public.thongbao_khaithac (
  id character varying NOT NULL,
  ref_tuyen character varying NOT NULL,
  ref_don_vi text,
  so_thong_bao text NOT NULL,
  ngay_ban_hanh date,
  ngay_bat_dau date,
  co_quan_ban_hanh text,
  hieu_luc text,
  loai_tb text,
  so_chuyen_khai_thac_thang integer,
  ghi_chu text,
  file_dinh_kem text,
  don_vi_kinh_doanh_van_tai text,
  related_bieudo_ids text,
  thong_bao_hien_thi text,
  dia_chi_sau_xac_nhap_dvkdvt text,
  ref_ben_di text,
  ref_ben_den text,
  ref_tinh_di text,
  ref_tinh_den text,
  ref_hanh_trinh text,
  ref_ma_so_tuyen text,
  ref_cu_ly text,
  lich_chieu_di text,
  lich_chieu_ve text,
  ref_kieu_lich text,
  so_dien_thoai text,
  so_giay_phep_kdvt text,
  ngay_cap_giay_phep_kdvt text,
  ref_luu_luong_con_lai text,
  ref_gian_cach_toi_thieu_phut text,
  gio_chieu_di text,
  gio_chieu_ve text,
  luu_luong_qh text,
  thoi_gian_gian_cach text,
  tinh_ql text,
  vc_vb_cham_dut_moi_nhat text,
  related_hoso_vanban_khaithacs text,
  related_phieu_giam_tan_suat_bieu_dos text,
  related_ls_giam_tan_suat_bieu_dos text,
  user_nhap text,
  thoi_gian_nhap text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT thongbao_khaithac_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  email character varying NOT NULL UNIQUE,
  password_hash character varying,
  name character varying,
  phone character varying,
  role character varying NOT NULL DEFAULT 'user'::character varying,
  is_active boolean NOT NULL DEFAULT true,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  ben_phu_trach uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_ben_phu_trach_fkey FOREIGN KEY (ben_phu_trach) REFERENCES public.locations(id)
);
CREATE TABLE public.vehicle_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  badge_number character varying,
  plate_number character varying NOT NULL,
  vehicle_id uuid,
  operator_id uuid,
  route_id uuid,
  badge_type character varying,
  route_code character varying,
  route_name character varying,
  issue_date date,
  expiry_date date,
  status character varying DEFAULT 'active'::character varying,
  is_active boolean NOT NULL DEFAULT true,
  operator_name character varying,
  operator_code character varying,
  metadata jsonb,
  synced_at timestamp with time zone,
  source character varying DEFAULT 'manual'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  tuyen_bus_code text,
  CONSTRAINT vehicle_badges_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_badges_vehicle_id_vehicles_id_fk FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT vehicle_badges_operator_id_operators_id_fk FOREIGN KEY (operator_id) REFERENCES public.operators(id),
  CONSTRAINT vehicle_badges_route_id_routes_id_fk FOREIGN KEY (route_id) REFERENCES public.routes(id)
);
CREATE TABLE public.vehicle_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vehicle_id uuid NOT NULL,
  document_type character varying NOT NULL,
  document_number character varying,
  issue_date date,
  expiry_date date,
  issuing_authority character varying,
  document_url text,
  notes text,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_documents_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_documents_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT vehicle_documents_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.vehicle_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  name character varying NOT NULL,
  code character varying UNIQUE,
  seat_count integer,
  description character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_id character varying UNIQUE,
  plate_number character varying NOT NULL UNIQUE,
  operator_id uuid,
  vehicle_type_id uuid,
  seat_count integer,
  brand character varying,
  model character varying,
  year_of_manufacture integer,
  color character varying,
  chassis_number character varying,
  engine_number character varying,
  registration_expiry date,
  insurance_expiry date,
  road_worthiness_expiry date,
  is_active boolean NOT NULL DEFAULT true,
  operational_status character varying DEFAULT 'active'::character varying,
  operator_name character varying,
  operator_code character varying,
  metadata jsonb,
  synced_at timestamp with time zone,
  source character varying DEFAULT 'manual'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  bed_capacity integer,
  image_url character varying,
  cargo_length integer,
  cargo_width integer,
  cargo_height integer,
  gps_provider character varying,
  gps_username character varying,
  gps_password character varying,
  province character varying,
  notes character varying,
  gps_url character varying,
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_operator_id_operators_id_fk FOREIGN KEY (operator_id) REFERENCES public.operators(id),
  CONSTRAINT vehicles_vehicle_type_id_vehicle_types_id_fk FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_types(id)
);